# Generated by Django 5.1.3 on 2025-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sub_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
