# Generated by Django 5.1.3 on 2025-02-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_image_alter_sub_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
